### ISSUE TITLE
Explain

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/automated-interpretation-pipeline#104]
https://main-web.populationgenomics.org.au/ohmr3-mendelian/reanalysis/2022-08-29/summary_output.html
Sample [13Y03696](https://seqr.populationgenomics.org.au/project/R0025_ohmr3_mendelian/family_page/F000593_13y01300)

ASPH variants which don't form a reciprocal comp-het, not exactly sure of the reason

**Comment by MattWellie** [comment]
Current behaviour opposite to expected, even in latest report version 
https://main-web.populationgenomics.org.au/ohmr3-mendelian/reanalysis/2023-01-16/summary_output.html

Variant coords ending *095 looks the more likely to be found as AD (completely absent from population data)

**Comment by MattWellie** [comment]
This is an error in the application of the MOI check to compound-het variants. Investigated:
- The variant in question is Cat. 1, so the MOI test is run under a partial penetrance model. 
- The family contains 2 samples, both affected.
- The paired variant [8:61548140](https://seqr.populationgenomics.org.au/variant_search/variant/8-61548140-G-T/family/F000593_13y01300) occurs in both family members, so it passes the dominant filter.
- The [8:61526095](https://seqr.populationgenomics.org.au/variant_search/variant/8-61526095-C-T/family/F000593_13y01300) variant is only present in one participant, the other is WT. As it does not explain the phenotype across all affected family members, it does not succeed under a dominant model.

This should also mean it doesn't succeed as a comp-het, and the comp-het pair also doesn't explain the whole family's phenotype.

**Comment by cassimons** [comment]
Great effort stepping through all of the logic here!  My read is that it seems to be doing exactly what we want it to. Yes there will be corner cases like this one where the outcome is slightly unintuitive, but I think that is ok. 

In terms of the family structure, I am hesitant to move to a flat family structure as if we do not have a pedigree then the chances of the phenotyping also being rubbish are much higher. Keeping it as is seems to be the way to go.
