### ISSUE TITLE
Noise Reduction - Polybase tracts

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/automated-interpretation-pipeline#12]
A number of the variants which are surviving the filtering and annotation process are predicted likely to be noise, in spite of quality filtering and VQSR. 

A key category of variants which can be presumptively excluded are those occurring in Poly-base tracts. This issue should serve as a discussion board for how to refine and implement this feature.

e.g. 
- where a variant is a poly-base indel within a sequence context which is also a stretch of > X of the same base, presumptively discard
- similar approach with di-nucleotide variants within a di-nucleotide repeat context

to clarify:
- remove completely?
- flag as artefact but retain in report?
- utilise frequency in joint-call with unrelated participants to estimate 'reality' of variant

**Comment by lgruen** [comment]
Is the broader question maybe how we want to handle microsatellites / STRs? E.g. is it worth including a relevant [variant catalog](https://github.com/Illumina/ExpansionHunter/blob/master/docs/04_VariantCatalogFiles.md)? @hopedisastro might be interested in this as well.

**Comment by hopedisastro** [comment]
If I'm understanding this correctly, the issue is determining the importance of in-repeat repeats/repeats found within a larger repetitive sequence.

**Comment by hopedisastro** [comment]
Also I would consider the noise:signal ratio across different motif lengths. I would expect more noise in homopolymer and dinucleotide runs compared to longer motifs and this may influence your approach to flagging.

**Comment by MattWellie** [comment]
I think ultimately this will boil down to the question of which variants we want to be called by different callers, and how to resolve any issues at the interfaces.
 
e.g. GATK is able to call indels, but where do we draw the line between InDel and STR such that when we bring in additional variant sources (e.g. EH), we are able to select high confidence indels from GATK, high confidence STRs from EH, and potentially scrap the rest. 

For this limited purpose, GATK records the flanking sequence context for small variants. Where the variant is a poly-base repeat within the context of a poly-base repeat, we have been asked by the clinical team to presumptively remove these from consideration. Further exposure to real data will help us get a better picture of how liberal we can be with this removal, but inclusion of STR callers for a different view of the same data would definitely be a way to change this issue from 'potentially removing real variants' to 'using multiple variant callers, each to their strengths'

**Comment by MattWellie** [comment]
https://hail.is/docs/0.2/hail.expr.LocusExpression.html#hail.expr.LocusExpression.sequence_context

**Comment by MattWellie** [comment]
There was no noise
