### ISSUE TITLE
Job dependency bug in generate_annotated_data

### ISSUE THREAD

**Issue by jeremiahwander** [populationgenomics/automated-interpretation-pipeline#297]
If `generate_clinvar_table()` has been run successfully and `generate_annotated_data()` has not then the dependency logic starting [here:L108](https://github.com/populationgenomics/automated-interpretation-pipeline/blob/7f2d4d797227561a2242afd59ca187509b6d2098/reanalysis/clinvar_runner.py#L108) results in a failed annotation job. 

I think the correct logic should be:

```python
if vep_jobs:
        if dependency:
            for job in vep_jobs:
                job.depends_on(dependency)
        dependency = vep_jobs[-1]
```

**Comment by MattWellie** [comment]
Ahhh, so if dependency is None but vep_jobs are populated the current code isn't updating the DAG correctly. I thought I fixed this but might have missed this scenario
