### ISSUE TITLE
Add family size to family metadata?

### ISSUE THREAD

**Issue by kdahlo** [populationgenomics/automated-interpretation-pipeline#310]
Family-level metadata currently includes "ext_id", "family_id", "members", "phenotypes", "panel_ids" and "panel_names".  Could we add family_type and/or family_size info (perhaps aligned with categories in "family_breakdown" in the run metadata) to each family? This would make it easier to sort outputs based on family characteristics.

**Comment by MattWellie** [comment]
I've made a PR to add a little tweak here, can you have a look and see if it will solve this?
