### ISSUE TITLE
Create Hail Query Stage

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/automated-interpretation-pipeline#4]
Port script https://github.com/populationgenomics/rare-disease/blob/initial_content/reanalysis/hail_filter_and_classify.py into this repository

- Requires relevant documentation
- Requires more testing
- Remove GCP dependence through CloudPathLib
- Remove Analysis-runner dependency where possible

**Comment by lgruen** [comment]
If we could run this without Dataproc, that would be awesome.
