### ISSUE TITLE
Report improvements

### ISSUE THREAD

**Issue by cassimons** [populationgenomics/automated-interpretation-pipeline#435]
Requests:
 - Can we replace the "phenotype match" column in the report with a coloured 👤? Any colour but pink (Z hates pink).  A gene level match and a panel match are similar concepts so we should present them in the same way.
 - Now that we have dropped cat2, we need to find a way to highlight any variant in "recent" new genes. My straw man for how this should work:
   - Have a configurable time delta of X months. Any gene that is "new" to panelApp in the past X months should get a "New" label
   - It would be great to distinguish between "new" to the mendeliome and "new" to and new to a family-specific panel. Can we make this distinction easily?
   - In the report we indicate new genes with a gold ⭐ next to the Gene symbol OR a blue ⭐ if it is just been added to a panel 
 - For the clinvar column:
  -  Should it be renamed to ClinVarbitration? 
  - And/or should we add a `?` with a hover over tooltip linking to ClinVarbitration? (only if the tool tips are supported in column titles, I can remember if they break with the sorting etc)
  -  Given the value "Pathogenic" is our aggregation of P and LP submissions, I wonder if we should display this as "P/LP" instead?

**Comment by MattWellie** [comment]
> Given the value "Pathogenic" is our aggregation of P and LP submissions, I wonder if we should display this as "P/LP" instead?

Closing this issue, with this as the last remaining point. This has been addressed on the ClinvArbitration side, and once we're ready to adapt to it in Talos we can pick that up and generate new ClinVar'b data
