### ISSUE TITLE
Changes to Cat2/Recent

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/automated-interpretation-pipeline#436]
From #435 

```
Now that we have dropped cat2, we need to find a way to highlight any variant in "recent" new genes. My straw man for how this should work:

- Have a configurable time delta of X months. Any gene that is "new" to panelApp in the past X months should get a "New" label

- It would be great to distinguish between "new" to the mendeliome and "new" to and new to a family-specific panel. Can we make this distinction easily?

- In the report we indicate new genes with a gold ⭐ next to the Gene symbol OR a blue ⭐ if it is just been added to a panel
```

Just to confirm up-front - implementing this would mean dropping Category 2 (and its associated more lenient logic) completely? 

We'd instead be in a situation where variants in any category can be flagged as 'new', but being new itself doesn't feed into the category analysis.

---

This all sounds doable using the Activity endpoint in PanelApp. I included something previously where I used the panel activity endpoint to poll for a specific panel version based on dates, but that was... janky, and differences between two versions of the same panel were kinda unsatisfying. 

Instead I can pull the Panel data as normal, then the activity log for the panel. That contains a date stamp for the event where each gene is marked as Green, or 'ready', e.g.

```
{
    "created": "2024-09-11T07:38:43.562302Z",
    "panel_name": "Mendeliome",
    "panel_id": 137,
    "panel_version": "1.2011",
    "user_name": "Zornitza Stark",
    "item_type": "entity",
    "text": "Marked gene: RNU2-2P as ready",
    "entity_name": "RNU2-2P",
    "entity_type": "gene"
  },
  {
    "created": "2024-09-11T07:38:43.547129Z",
    "panel_name": "Mendeliome",
    "panel_id": 137,
    "panel_version": "1.2011",
    "user_name": "Zornitza Stark",
    "item_type": "entity",
    "text": "Gene: rnu2-2p has been classified as Green List (High Evidence).",
    "entity_name": "RNU2-2P",
    "entity_type": "gene"
  },
```

It would be a case of parsing these log entries for all green genes, identifying the point at which each gene was marked as green, and seeing if that falls in the pre-determined time delta to classify it as 'new'.

---

Time Delta - this would be in config, but 2 months sounds like a decent window. Maybe 2.5? We typically run reports every month, so that would be enough time that an analyst could miss one report cycle without completely missing that a gene was recently added. The .5 buffer would mean that there's some leeway in what specific part of the month the reports are run.

This wouldn't interact specifically with the 'first seen' stamp. A variant could appear as 'new' for multiple reports in a row, but the first date seen would be a fixed value. Analysts are always free to filter the report using `> DATE` syntax.

---

New in the Mendeliome vs. phenotype matched panel would be relatively simple - the notion of 'new' I've been storing is a list of panel IDs, rather than a Boolean. That's already in use when deciding if Cat. 2 applies to each individual in the analysis, so I'd keep that behaviour, and render it in the report with either a mendeliome or a feature panel star (or both).

---

This report is going to need a figure legend for the various icons and tooltips 😆

**Comment by cassimons** [comment]
> Just to confirm up-front - implementing this would mean dropping Category 2 (and its associated more lenient logic) completely? We'd instead be in a situation where variants in any category can be flagged as 'new', but being new itself doesn't feed into the category analysis.

This is my preference. I think the concept of a gene being recently identified is orthogonal to the variant-level filtering and cat2 is an ugly mixing of the concepts. My logic is that new genes should not receive any distinct variant-level logic, but the should be flagged for extra review in case they have not been considered before in previous analyses. 

> Time Delta - this would be in config, but 2 months sounds like a decent window. Maybe 2.5? We typically run reports every month, so that would be enough time that an analyst could miss one report cycle without completely missing that a gene was recently added. The .5 buffer would mean that there's some leeway in what specific part of the month the reports are run.

I think a longer window is needed here. In this use case "new" is not relative to the previous Talos report, but rather it is to indicate that there is a recent change in knowledge so the analyst should pay closer attention. As you say, this will be distinct from the 'first seen' time stamp, which is the date filtering should be based on.

> This report is going to need a figure legend for the various icons and tooltips 😆
Yea, we still need to overhaul this whole report at some point.

**Comment by MattWellie** [comment]
With PanelApp Aus I think it's mature enough at this point that we could push the 'new' window out to 6+ months without issues. Much longer than that and some might just be perceived as 'new' because the panel was being constructed, rather than recent knowledge being added to a mature panel. That is a bit of a hand-wavey guess about the timeline, maybe these have been fixed for longer than I remember
