### ISSUE TITLE
Much stricter thresholds

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/automated-interpretation-pipeline#70]
Some points from the meeting earlier, for discussion 

- Currently no specific gnomad AC count on Hemizygote MOI test
- Gnomad Homs - > 1 should be enough to dismiss any variant? > 2?
- Add gnomad exomes and genomes counts when counting the number of homs/hemi in population data?
  - I'm not super enthusiastic about this, if we're soon (?) moving to a 700k genome Gnomad v4
- AC within joint call should be much lower than 10%. Suggesting a shifting threshold so that we remain sensitive to segregation of causative variants within large families no matter the cohort size:
    - AC < 100, 5% cut-off?
    - 100 < AC < 1000, 1% cut-off?
    - AC > 1000, 0.5%?
    - Should these be specific numbers, or percentages?

**Comment by pfdefazio** [comment]
Thanks @MattWellie. I can comment relating to VCGS clinical process in a rare disease context:

> Currently no specific gnomad AC count on Hemizygote MOI test

We'd typically disregard >=1 hemi as long as there are multiple hets ('multiple' is vague and up for discussion...>2?).

> Add gnomad exomes and genomes counts when counting the number of homs/hemi in population data?

Also not enthused by this.

> Gnomad Homs - > 1 should be enough to dismiss any variant? > 2?

We'd typically disregard any variant with >=1 het and >=1 hom. >=2 homs is conservative, I wouldn't go higher than that.

> AC within joint call should be much lower than 10%. Suggesting a shifting threshold so that we remain sensitive to segregation of causative variants within large families no matter the cohort size:

We use:
- AC >= 500, 1%;  OR 
- variant count needs to be >=5 (so 2% at AC = 250, 5% at AC = 100, etc) where our AC < 500

**Comment by MattWellie** [comment]
I like that AC/AN threshold. I'm going to switch it up so that we'll remove variants with AC > 1%, but no filter applied to AC<=5
