### ISSUE TITLE
Hail's de novo implementation is too restrictive

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/automated-interpretation-pipeline#78]
# Context

Rather than implement a bespoke de novo finding algorithm, we are using [Hail's built-in implementation](https://hail.is/docs/0.2/methods/genetics.html#hail.methods.de_novo). This takes a number of attributes into account other than the called genotypes: depths (absolute and ratios), genotype probability likelihoods, GQ, population allele frequency, etc...

In practice we are finding this approach too restrictive. We have already had to remove the 'confidence threshold' we had in place as many of the (cleanly called, unambiguous) de novo calls in our dataset were being flagged as 'low confidence'.

Now we are finding that even without filtering for confidence, the algorithm is taking cleanly called de novo variants and not even recognising them as low confidence de novo calls. This is just a bit silly, and this method is doing more damage than good. 

## Solution

Implement a quick and dirty custom version, borrowing from the current hail code.

- generate a trio matrix (hail structure) from the callset and pedigree
- identify each trio where the parents have no call, and the proband (child in the pedigree) has a het call (autosomal, female X), or hom call (male X)
- Annotate those identified sample IDs back onto the original MT

## Problems? 

- What happens if/when this is extended to more complex pedigrees? see what happens if we generate a trio matrix from a quad
- what genotypes are we looking for in MT
- what genotypes are we looking for in Y (currently irrelevant)

## Optional bonus overtime

If we're going all custom on this, it wouldn't take too much logic to transform this into a UPD identifier?!

**Comment by cassimons** [comment]
I agree that falling back to this simple logic seems like a good idea at this point. A few thoughts:

- UDP detection. I agree this should be on the roadmap, but so far we had discussed this in the context of reporting (very) large chromosomal regions with high ROH. This would not be specific to UPD, but would be functional on singletons.
-  complex pedigrees: interesting question. I wonder if we should treat this a bit like the low-penetrance escape we are using for cat1? ie if one affected has a qualifying denovo then we report it regardless to cover the situations where the diagnosis of the 2nd affected may be less certain (this is probably a concept we need to consider more broadly).
